// User model (for registration and login)

package com.rpgsheet.backend.models;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "users")
@Data // Generate getters, setters, etc. automatically
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false) // Doesn't allow the same username twice on the database, neither a null username
    private String username; // Email

    @Column(nullable = false)
    private String password;

    // Constructors

    // Empty constructor
    public User() {}

    // Without id (id is generated by the database)
    public User(String username, String password) { // Dependency Injection
        this.username = username;
        this.password = password;
    }

}
